name: Trigger for MR

on:
  pull_request:
    branches: [ main ]
    types: [closed]

jobs:
  trigger:
    if: ${{ github.event.pull_request.merged }}
    runs-on: alpine:curl
    steps:
      - run: curl http://34.229.75.164:8080/generic-webhook-trigger/invoke?token=secrettoken123
