name: Trigger for MR

on:
  pull_request:
    branches: [ main ]
    types: [closed]

jobs:
  trigger:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
    - run: git clone https://github.com/lnasyrov/pet-project.git
    - run: java -jar pet-project/jenkins-cli.jar -s http://34.229.75.164:8080/ -auth transformer:11ecd41015e0139da752c9306b34603d4e build Pipeline-1

