name: Trigger for pipeline

on:
  pull_request:
    branches: [ main ]
    types: [closed]

jobs:
  trigger_pipeline:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-18.04
    env:
      TOKEN: ${{ TOKEN.TOKEN }}
      USER: ${{ TOKEN.USER }}
      JENKINS_URL: ${{ TOKEN.JENKINS_URL }}
    steps:
    - run: git clone https://github.com/lnasyrov/pet-project.git
    - run: java -jar pet-project/jenkins-cli.jar -s "$JENKINS_URL" -auth "$USER":"$TOKEN" build Pipeline-1

