name: Trigger for MR

on:
  pull_request:
    branches: [ main ]
    types: [closed]

jobs:
  trigger:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
    - name: trigger pipeline-1
      uses: appleboy/jenkins-action@master
      with:
        url: "http://http://34.229.75.164:8080/"
        user: "admin"
        token: secret123
        job: "Pipeline-1"
