name: Trigger for MR

on:
  pull_request:
    branches: [ main ]
    types: [closed]

jobs:
  trigger:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
    - name: trigger pipeline-1
      uses: appleboy/jenkins-action@master
      with:
        url: "http://34.229.75.164:8080"
        user: "transformer"
        token: "1102ff653aa4950d8e35e9c7432e8bcbe2"
        job: "Pipeline-1"
