name: Trigger for MR_validation

on:
  pull_request:
    branches: [ main ]
    types: [opened]
    
jobs:
  trigger_validation:
    runs-on: ubuntu-18.04
    steps:
    - run: git clone https://github.com/lnasyrov/pet-project.git
    - run: java -jar pet-project/jenkins-cli.jar -s http://34.229.75.164:8080/ -auth admin:11ecd41015e0139da752c9306b34603d4e build MR_Validation
