name: Trigger for MR_validation

on:
  pull_request:
    branches: [ main ]
    types: [opened]
    
jobs:
  trigger_validation:
    runs-on: ubuntu-18.04
    env:
      TOKEN1: ${{ secrets.TOKEN1 }}
      USER1: ${{ secrets.USER1 }}
      JENKINS_URL1: ${{ secrets.JENKINS_URL1 }}
    steps:
    - run: git clone https://github.com/lnasyrov/pet-project.git
    - run: java -jar pet-project/jenkins-cli.jar -s $JENKINS_URL1 -auth $USER1:$TOKEN1 build MR_Validation
