name: Trigger for MR_validation

on:
  pull_request:
    branches: [ main ]
    types: [opened]
    
jobs:
  trigger_validation:
    runs-on: ubuntu-18.04
    env:
      TOKEN: '${{ secrets.TOKEN }}'
      USER: '${{ secrets.USER }}'
      JENKINS_URL: '${{ secrets.JENKINS_URL }}'
    steps:
    - run: echo $TOKEN
    - run: echo $JENKINS_URL
    - run: echo '$USER'
    - run: echo '${{ USER }}'
    - run: git clone https://github.com/lnasyrov/pet-project.git
    - run: java -jar pet-project/jenkins-cli.jar -s "$JENKINS_URL" -auth "$USER":"$TOKEN" build MR_Validation
